// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"------------------------","status":false,"description":"----------------------------------------------------------------------------------","parameters":{}},
{"name":"-Online","status":false,"description":"","parameters":{}},
{"name":"------------------------","status":false,"description":"----------------------------------------------------------------------------------","parameters":{}},
{"name":"OrangeCustomEvents","status":true,"description":"This plugin Will let you add or copy events to the current map","parameters":{}},
{"name":"OrangeCustomEventCreator","status":true,"description":"This plugin Will let you create virtual events with script calls","parameters":{}},
{"name":"MMO_Core","status":true,"description":"MMORPG Maker MV - Core","parameters":{"Server Location":"http://133.209.8.32:8097/"}},
{"name":"MMO_Core_Player","status":true,"description":"MMORPG Maker MV - Core Handling Player","parameters":{"Mouse Movements":"true","Use Native Respawn":"false"}},
{"name":"MMO_Core_Players","status":true,"description":"MMORPG Maker MV - Core Handling Players","parameters":{}},
{"name":"MMO_Core_Party","status":true,"description":"MMORPG Maker MV - Core Handling Parties","parameters":{}},
{"name":"MMO_Core_Party_Combat","status":true,"description":"MMORPG Maker MV - Core Handling Combat in Party","parameters":{}},
{"name":"MMO_Core_Bank","status":true,"description":"MMORPG Maker MV - Core Handling Bank","parameters":{}},
{"name":"MMO_ChatBox","status":true,"description":"MMORPG Maker MV - ChatBox","parameters":{"chatPosition":"BOTTOM LEFT"}},
{"name":"MMO_LoginForm","status":true,"description":"MMORPG Maker MV - Login Form","parameters":{"allowAccountCreation":"Yes"}},
{"name":"MMO_Overhead","status":true,"description":"Add name over actors name","parameters":{}},
{"name":"------------------------","status":false,"description":"----------------------------------------------------------------------------------","parameters":{}},
{"name":"-System","status":false,"description":"","parameters":{}},
{"name":"------------------------","status":false,"description":"----------------------------------------------------------------------------------","parameters":{}},
{"name":"Mano_InputConfig","status":true,"description":"コントローラ(ゲームパッド)・キーボードの設定を変更できます。\r\nユーザーが入力を拡張する場合の補助も行います。","parameters":{"mapperOk":"{\"en\":\"ok\",\"jp\":\"決定\"}","mapperCancel":"{\"en\":\"cancel\",\"jp\":\"キャンセル\"}","mapperShift":"{\"en\":\"dash\",\"jp\":\"ダッシュ\"}","mapperMenu":"{\"en\":\"menu\",\"jp\":\"メニュー\"}","mapperEscape":"{\"en\":\"menu/cancel\",\"jp\":\"メニュー/キャンセル\"}","mapperPageup":"{\"en\":\"next\",\"jp\":\"次\"}","mapperPagedown":"{\"en\":\"prev\",\"jp\":\"前\"}","mapperDelete":"{\"en\":\"delete\",\"jp\":\"設定を消去\"}","extendsMapper":"[]","overwriteWarning":"true","GamepadIsNotConnected":"\"ゲームパッドが接続されていません\\nボタンを押して再度試してください\"","needButtonDetouch":"\"コンフィグを終了するためには\\nボタンから手を放してください。\"","apply":"{\"width\":\"4\",\"text\":\"{\\\"jp\\\":\\\"設定を保存\\\",\\\"en\\\":\\\"save settings\\\"}\"}","rollback":"{\"width\":\"4\",\"text\":\"{\\\"jp\\\":\\\"変更前に戻す\\\",\\\"en\\\":\\\"rollback\\\"}\"}","reset":"{\"width\":\"4\",\"text\":\"{\\\"jp\\\":\\\"初期設定に戻す\\\",\\\"en\\\":\\\"reset\\\"}\"}","WASD":"{\"width\":\"3\",\"text\":\"{\\\"jp\\\":\\\"WASD\\\",\\\"en\\\":\\\"WASD\\\"}\"}","changeLayout":"{\"width\":\"3\",\"text\":\"{\\\"jp\\\":\\\"JIS/US\\\",\\\"en\\\":\\\"JIS/US\\\"}\"}","exit":"{\"width\":\"3\",\"text\":\"{\\\"jp\\\":\\\"やめる\\\",\\\"en\\\":\\\"exit\\\"}\"}","gamepadConfigCommandText":"{\"en\":\"gamepad config\",\"jp\":\"ゲームパッドコンフィグ\"}","keyConfigCommandText":"{\"en\":\"keyboard config\",\"jp\":\"キーコンフィグ\"}"}}
];
